### ISSUE TITLE
Does this project works in sublime text 4?

### ISSUE THREAD

**Issue by ghost** [jw0z96/compiler-explorer-sublime#1]
Hi @jw0z96 

Greetings.

I downloaded the plugin into `/home/user/.config/sublime-text-3/Packages` and in the console I have passed:

`view.run_command('CompilerExplorer', {'file':'/home/user/Downloads/test.py', 'tmpFilePath':'/home/user/Downloads'}) `

but I got:

`couldn't find *.o!!!`

could you tell me what is the proper way to set up this plugin in order to get a compiler explorer as the [vscode plugin extension](https://github.com/MRobertEvers/vscode-compiler-explorer) (or is this a different plugin?)

Thanks

**Comment by jw0z96** [comment]
> Hi @jw0z96
> 
> Greetings.
> 
> I downloaded the plugin into `/home/user/.config/sublime-text-3/Packages` and in the console I have passed:
> 
> `view.run_command('CompilerExplorer', {'file':'/home/user/Downloads/test.py', 'tmpFilePath':'/home/user/Downloads'}) `
> 
> but I got:
> 
> `couldn't find *.o!!!`
> 
> could you tell me what is the proper way to set up this plugin in order to get a compiler explorer as the [vscode plugin extension](https://github.com/MRobertEvers/vscode-compiler-explorer) (or is this a different plugin?)
> 
> Thanks

Hi @danielTobon43,

Unfortunately I haven't tested this in Sublime Text 4, as I haven't used Sublime Text (either 3 or 4) in a while... I will likely rename this project and archive it, as I am neither affliated with Compiler Explorer (or any other editor extensions/implementations), or have any intentions of maintaining this project - sorry!

All this script really does is watch for changes on source files, and copies the output of the corresponding object file disassembly into a read-only Sublime buffer (using `objdump` & `c++filt` to partially emulate Compiler Explorer's functionality). It should be fairly straight forward to write a similar python script for your own project, and I'm sure Sublime 4's plugin/extension API still provides the same functionality required to show it in your editor.

Thanks
